[build-system]
requires = [
    "setuptools>=41.2.0",
    "pandas>=1.5.2",
    "requests>=2.28.1"
]
build-backend = "setuptools.build_meta"

[project]
name = "com.castsoftware.uc.python.common"
version = "0.1.2"
authors = [
  { name="Nevin Kaplan", email="n.kaplan@castsoftware.com" }
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/CAST-Extend/com.castsoftware.uc.python.common"
"Bug Tracker" = "https://github.com/CAST-Extend/com.castsoftware.uc.python.common/issues"

