[tool.poetry]
name = "tap-prefect"
version = "0.2.0"
description = "`tap-prefect` is a Singer tap for prefect, built with the Meltano Singer SDK."
authors = ["Datateer Dev"]
keywords = [
    "ELT",
    "prefect",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.12,>=3.7.1"
singer-sdk = { version="^0.18.0"}
fs-s3fs = { version = "^1.1.1", optional = true}
requests = "^2.28.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
tox = "^3.27.0"
flake8 = "^3.9.2"
black = "^22.12.0"
pydocstyle = "^6.2.1"
mypy = "^0.991"
isort = "^5.11.4"
types-requests = "^2.28.11.7"

[tool.poetry.extras]
s3 = ["fs-s3fs"]

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "tap_prefect"

[build-system]
requires = ["poetry-core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
tap-prefect = 'tap_prefect.tap:TapPrefect.cli'

[tool.semantic_release]
version_variable = [
    "pyproject.toml:version"
]
branch = "main"
upload_to_pypi = true
upload_to_release = true
build_command = "pip install poetry && poetry build"