[tool.poetry]
name = "use-case-outcome"
version = "1.1.0"
description = "Package for collecting information about the execution of a use case"
authors = ["Ross Bown <rossbo@softcat.com>"]
readme = "README.md"
packages = [{include = "use_case_outcome"}]

[tool.poetry.dependencies]
python = "^3.7"
swimlane = "^10.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
