[tool.poetry]
name = "webhook_server"
version = "0.1.1"
description = "Create a webhook server with Flask to forward Datadog alerts to Telegram"
authors = ["daisukixci <daisuki@tuxtrooper.com>"]
maintainers = ["daisukixci <daisuki@tuxtrooper.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://gitlab.com/daisukixci/webhook_server"
repository = "https://gitlab.com/daisukixci/webhook_server"
documentation = "https://gitlab.com/daisukixci/webhook_server/-/blob/main/README.md"
keywords = ["datadog", "webhook", "telegram"]


[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.2.2"
Flask-HTTPAuth = "^4.7.0"
Flask-BasicAuth = "^0.2.0"

[tool.poetry.dev-dependencies]
pytest = "7.2.1"
pytest-cov = "^4.0.0"
pre-commit = "^2.21.0"
flake8 = "^6.0.0"
mypy = "^0.991"
isort = "^5.11.4"
black = {version = "^22.12.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
