[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "EclipsingBinaries"
version = "1.0.4"
authors = [
  { name="Kyle Koeller"},
]
description = "A Python project for Ball State University's Variable Star Research Group"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/kjkoeller/Binary_Star_Research_Package"
"Bug Tracker" = "https://github.com/kjkoeller/Binary_Star_Research_Package/issues"