[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "revolutionhtl"
version = "0.0.7"
authors = [
  { name="José Antonio Ramírez-Rafael", email="jose.ramirezra@cinvestav.mx" },
]
description = "REvolutionH-tl: Reconstruction of Evolutionary Histories tool"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["Evolution reconstruction",
            "Trees inference",
            "Trees reconciliation", 
            "Best match graphs",
            "Orthology",
            ]
dependencies = [
    "networkx >= 2.8",
    "pandas >= 1.4.2",
    "argparse >= 1.1",
    "os",
    "numpy >= 1.22.3",
    "tqdm >= 4.63.0",
    "itertools",
    "collections",
#    "matplotlib >= 3.5.2",
#    "pydot",
    ]

[project.urls]
"Homepage" = "https://gitlab.com/jarr.tecn/revolutionh-tl"
"Bug Tracker" = "https://gitlab.com/jarr.tecn/revolutionh-tl/issues"
