[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "pysqlake"
version = "0.0.2"
authors = [
  { name="David Aisenthal", email="david@upsolver.com" },
]
description = "Run Upsolver SQLake commands using Python"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
"upsolver-cli >= 0.6.4"
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"