[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CaptionedFileFormat"
version = "1.0.1"
authors = [
  {name="Oakchris1955"},
]
description = "A Python wrapper for the Captioned File (CPTF) file format"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Oakchris1955/Captioned-File"
"Bug Tracker" = "https://github.com/Oakchris1955/Captioned-File/issues"