[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pymeddra"
version = "0.0.6"
authors = [
  { name="Karel D'Oosterlinck", email="kareldoosterlinck@gmail.com" },
]
description = "Parse and use MedDRA in Python."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
 'pydantic>=1.10.4',
]

[project.urls]
"Homepage" = "https://github.com/KarelDO/pymeddra"
"Bug Tracker" = "https://github.com/KarelDO/pymeddra/issues"